//
// MobileAuthorizationAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class MobileAuthorizationAPI {
    /**
     CreateMobileAuthorizationCode
     - parameter body: (body) An object containing the fields to POST for the request.

See the corresponding object definition for field details. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createMobileAuthorizationCode(body: CreateMobileAuthorizationCodeRequest, completion: @escaping ((_ data: CreateMobileAuthorizationCodeResponse?,_ error: Error?) -> Void)) {
        createMobileAuthorizationCodeWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     CreateMobileAuthorizationCode
     - POST /mobile/authorization-code
     - Generates code to authorize a mobile application to connect to a Square card reader  Authorization codes are one-time-use and expire __60 minutes__ after being issued.  __Important:__ The `Authorization` header you provide to this endpoint must have the following format:  ``` Authorization: Bearer ACCESS_TOKEN ```  Replace `ACCESS_TOKEN` with a [valid production authorization credential](https://docs.connect.squareup.com/get-started#step-4-understand-the-different-application-credentials).
     - OAuth:
       - type: oauth2
       - name: oauth2
     - examples: [{contentType=application/json, example={
  "authorization_code" : "YOUR_MOBILE_AUTHZ_CODE",
  "expires_at" : "2019-01-10T19:42:08Z"
}}]
     - parameter body: (body) An object containing the fields to POST for the request.

See the corresponding object definition for field details. 

     - returns: RequestBuilder<CreateMobileAuthorizationCodeResponse> 
     */
    open class func createMobileAuthorizationCodeWithRequestBuilder(body: CreateMobileAuthorizationCodeRequest) -> RequestBuilder<CreateMobileAuthorizationCodeResponse> {
        let path = "/mobile/authorization-code"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<CreateMobileAuthorizationCodeResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
