//
// OAuthAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class OAuthAPI {
    /**
     ObtainToken
     - parameter body: (body) An object containing the fields to POST for the request.

See the corresponding object definition for field details. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func obtainToken(body: ObtainTokenRequest, completion: @escaping ((_ data: ObtainTokenResponse?,_ error: Error?) -> Void)) {
        obtainTokenWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     ObtainToken
     - POST /oauth2/token
     - Returns an OAuth access token.   The endpoint supports distinct methods of obtaining OAuth access tokens.  Applications specify a method by adding the `grant_type` parameter  in the request and also provide relevant information.  For more information, see [OAuth access token management](/authz/oauth/how-it-works#oauth-access-token-management).   __Note:__ Regardless of the method application specified, the endpoint always returns two items; an OAuth access token and  a refresh token in the response.   __OAuth tokens should only live on secure servers. Application clients should never interact directly with OAuth tokens__.
     - examples: [{contentType=application/json, example={
  "access_token" : "ACCESS_TOKEN",
  "token_type" : "bearer",
  "expires_at" : "2006-01-02T15:04:05Z",
  "merchant_id" : "MERCHANT_ID"
}}]
     - parameter body: (body) An object containing the fields to POST for the request.

See the corresponding object definition for field details. 

     - returns: RequestBuilder<ObtainTokenResponse> 
     */
    open class func obtainTokenWithRequestBuilder(body: ObtainTokenRequest) -> RequestBuilder<ObtainTokenResponse> {
        let path = "/oauth2/token"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<ObtainTokenResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     RenewToken
     - parameter body: (body) An object containing the fields to POST for the request.

See the corresponding object definition for field details.      - parameter clientId: (path) Your application&#x27;s ID, available from the [application dashboard](https://connect.squareup.com/apps). 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func renewToken(body: RenewTokenRequest, clientId: String, completion: @escaping ((_ data: RenewTokenResponse?,_ error: Error?) -> Void)) {
        renewTokenWithRequestBuilder(body: body, clientId: clientId).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     RenewToken
     - POST /oauth2/clients/{client_id}/access-token/renew
     - `RenewToken` is deprecated. For information about refreshing OAuth access tokens, see  [Renew OAuth Token](https://developer.squareup.com/docs/oauth-api/cookbook/renew-oauth-tokens).   Renews an OAuth access token before it expires.  OAuth access tokens besides your application's personal access token expire after __30 days__. You can also renew expired tokens within __15 days__ of their expiration. You cannot renew an access token that has been expired for more than 15 days. Instead, the associated user must re-complete the OAuth flow from the beginning.  __Important:__ The `Authorization` header for this endpoint must have the following format:  ``` Authorization: Client APPLICATION_SECRET ```  Replace `APPLICATION_SECRET` with the application secret on the Credentials page in the [application dashboard](https://connect.squareup.com/apps).
     - API Key:
       - type: apiKey Authorization 
       - name: oauth2ClientSecret
     - examples: [{contentType=application/json, example={
  "access_token" : "ACCESS_TOKEN",
  "token_type" : "bearer",
  "expires_at" : "2006-01-02T15:04:05Z",
  "merchant_id" : "MERCHANT_ID"
}}]
     - parameter body: (body) An object containing the fields to POST for the request.

See the corresponding object definition for field details.      - parameter clientId: (path) Your application&#x27;s ID, available from the [application dashboard](https://connect.squareup.com/apps). 

     - returns: RequestBuilder<RenewTokenResponse> 
     */
    open class func renewTokenWithRequestBuilder(body: RenewTokenRequest, clientId: String) -> RequestBuilder<RenewTokenResponse> {
        var path = "/oauth2/clients/{client_id}/access-token/renew"
        let clientIdPreEscape = "\(clientId)"
        let clientIdPostEscape = clientIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{client_id}", with: clientIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<RenewTokenResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     RevokeToken
     - parameter body: (body) An object containing the fields to POST for the request.

See the corresponding object definition for field details. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func revokeToken(body: RevokeTokenRequest, completion: @escaping ((_ data: RevokeTokenResponse?,_ error: Error?) -> Void)) {
        revokeTokenWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     RevokeToken
     - POST /oauth2/revoke
     - Revokes an access token generated with the OAuth flow.  If an account has more than one OAuth access token for your application, this endpoint revokes all of them, regardless of which token you specify. When an OAuth access token is revoked, all of the active subscriptions associated with that OAuth token are canceled immediately.  __Important:__ The `Authorization` header for this endpoint must have the following format:  ``` Authorization: Client APPLICATION_SECRET ```  Replace `APPLICATION_SECRET` with the application secret on the Credentials page in the [application dashboard](https://connect.squareup.com/apps).
     - API Key:
       - type: apiKey Authorization 
       - name: oauth2ClientSecret
     - examples: [{contentType=application/json, example={
  "success" : true
}}]
     - parameter body: (body) An object containing the fields to POST for the request.

See the corresponding object definition for field details. 

     - returns: RequestBuilder<RevokeTokenResponse> 
     */
    open class func revokeTokenWithRequestBuilder(body: RevokeTokenRequest) -> RequestBuilder<RevokeTokenResponse> {
        let path = "/oauth2/revoke"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<RevokeTokenResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
