//
// ReportingAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class ReportingAPI {
    /**
     ListAdditionalRecipientReceivableRefunds
     - parameter locationId: (path) The ID of the location to list AdditionalRecipientReceivableRefunds for.      - parameter beginTime: (query) The beginning of the requested reporting period, in RFC 3339 format.  See [Date ranges](#dateranges) for details on date inclusivity/exclusivity.  Default value: The current time minus one year. (optional)     - parameter endTime: (query) The end of the requested reporting period, in RFC 3339 format.  See [Date ranges](#dateranges) for details on date inclusivity/exclusivity.  Default value: The current time. (optional)     - parameter sortOrder: (query) The order in which results are listed in the response (&#x60;ASC&#x60; for oldest first, &#x60;DESC&#x60; for newest first).  Default value: &#x60;DESC&#x60; (optional)     - parameter cursor: (query) A pagination cursor returned by a previous call to this endpoint. Provide this to retrieve the next set of results for your original query.  See [Pagination](/basics/api101/pagination) for more information. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func listAdditionalRecipientReceivableRefunds(locationId: String, beginTime: String? = nil, endTime: String? = nil, sortOrder: String? = nil, cursor: String? = nil, completion: @escaping ((_ data: ListAdditionalRecipientReceivableRefundsResponse?,_ error: Error?) -> Void)) {
        listAdditionalRecipientReceivableRefundsWithRequestBuilder(locationId: locationId, beginTime: beginTime, endTime: endTime, sortOrder: sortOrder, cursor: cursor).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     ListAdditionalRecipientReceivableRefunds
     - GET /v2/locations/{location_id}/additional-recipient-receivable-refunds
     - Returns a list of refunded transactions (across all possible originating locations) relating to monies credited to the provided location ID by another Square account using the `additional_recipients` field in a transaction.  Max results per [page](#paginatingresults): 50
     - OAuth:
       - type: oauth2
       - name: oauth2
     - examples: [{contentType=application/json, example={
  "receivable_refunds" : [ {
    "id" : "Ge2OT7KA6XAg1GC15qs5S",
    "receivable_id" : "ISu5xwxJ5v0CMJTQq7RvqyMF",
    "refund_id" : "b27436d1-7f8e-5610-45c6-417ef71434b4-SW",
    "transaction_location_id" : "18YC4JDH91E1H",
    "amount_money" : {
      "amount" : 10,
      "currency" : "USD"
    },
    "created_at" : "2016-01-20T22:57:56Z"
  } ]
}}]
     - parameter locationId: (path) The ID of the location to list AdditionalRecipientReceivableRefunds for.      - parameter beginTime: (query) The beginning of the requested reporting period, in RFC 3339 format.  See [Date ranges](#dateranges) for details on date inclusivity/exclusivity.  Default value: The current time minus one year. (optional)     - parameter endTime: (query) The end of the requested reporting period, in RFC 3339 format.  See [Date ranges](#dateranges) for details on date inclusivity/exclusivity.  Default value: The current time. (optional)     - parameter sortOrder: (query) The order in which results are listed in the response (&#x60;ASC&#x60; for oldest first, &#x60;DESC&#x60; for newest first).  Default value: &#x60;DESC&#x60; (optional)     - parameter cursor: (query) A pagination cursor returned by a previous call to this endpoint. Provide this to retrieve the next set of results for your original query.  See [Pagination](/basics/api101/pagination) for more information. (optional)

     - returns: RequestBuilder<ListAdditionalRecipientReceivableRefundsResponse> 
     */
    open class func listAdditionalRecipientReceivableRefundsWithRequestBuilder(locationId: String, beginTime: String? = nil, endTime: String? = nil, sortOrder: String? = nil, cursor: String? = nil) -> RequestBuilder<ListAdditionalRecipientReceivableRefundsResponse> {
        var path = "/v2/locations/{location_id}/additional-recipient-receivable-refunds"
        let locationIdPreEscape = "\(locationId)"
        let locationIdPostEscape = locationIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{location_id}", with: locationIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "begin_time": beginTime, 
                        "end_time": endTime, 
                        "sort_order": sortOrder, 
                        "cursor": cursor
        ])

        let requestBuilder: RequestBuilder<ListAdditionalRecipientReceivableRefundsResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     ListAdditionalRecipientReceivables
     - parameter locationId: (path) The ID of the location to list AdditionalRecipientReceivables for.      - parameter beginTime: (query) The beginning of the requested reporting period, in RFC 3339 format.  See [Date ranges](#dateranges) for details on date inclusivity/exclusivity.  Default value: The current time minus one year. (optional)     - parameter endTime: (query) The end of the requested reporting period, in RFC 3339 format.  See [Date ranges](#dateranges) for details on date inclusivity/exclusivity.  Default value: The current time. (optional)     - parameter sortOrder: (query) The order in which results are listed in the response (&#x60;ASC&#x60; for oldest first, &#x60;DESC&#x60; for newest first).  Default value: &#x60;DESC&#x60; (optional)     - parameter cursor: (query) A pagination cursor returned by a previous call to this endpoint. Provide this to retrieve the next set of results for your original query.  See [Pagination](/basics/api101/pagination) for more information. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func listAdditionalRecipientReceivables(locationId: String, beginTime: String? = nil, endTime: String? = nil, sortOrder: String? = nil, cursor: String? = nil, completion: @escaping ((_ data: ListAdditionalRecipientReceivablesResponse?,_ error: Error?) -> Void)) {
        listAdditionalRecipientReceivablesWithRequestBuilder(locationId: locationId, beginTime: beginTime, endTime: endTime, sortOrder: sortOrder, cursor: cursor).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     ListAdditionalRecipientReceivables
     - GET /v2/locations/{location_id}/additional-recipient-receivables
     - Returns a list of receivables (across all possible sending locations) representing monies credited to the provided location ID by another Square account using the `additional_recipients` field in a transaction.  Max results per [page](#paginatingresults): 50
     - OAuth:
       - type: oauth2
       - name: oauth2
     - examples: [{contentType=application/json, example={
  "receivables" : [ {
    "id" : "ISu5xwxJ5v0CMJTQq7RvqyMF",
    "transaction_id" : "KnL67ZIwXCPtzOrqj0HrkxMF",
    "transaction_location_id" : "18YC4JDH91E1H",
    "amount_money" : {
      "amount" : 20,
      "currency" : "USD"
    },
    "created_at" : "2016-01-19T15:12:41Z",
    "refunds" : [ {
      "id" : "Ge2OT7KA6XAg1GC15qs5S",
      "receivable_id" : "ISu5xwxJ5v0CMJTQq7RvqyMF",
      "refund_id" : "b27436d1-7f8e-5610-45c6-417ef71434b4-SW",
      "transaction_location_id" : "18YC4JDH91E1H",
      "amount_money" : {
        "amount" : 10,
        "currency" : "USD"
      },
      "created_at" : "2016-01-20T22:57:56Z"
    } ]
  } ]
}}]
     - parameter locationId: (path) The ID of the location to list AdditionalRecipientReceivables for.      - parameter beginTime: (query) The beginning of the requested reporting period, in RFC 3339 format.  See [Date ranges](#dateranges) for details on date inclusivity/exclusivity.  Default value: The current time minus one year. (optional)     - parameter endTime: (query) The end of the requested reporting period, in RFC 3339 format.  See [Date ranges](#dateranges) for details on date inclusivity/exclusivity.  Default value: The current time. (optional)     - parameter sortOrder: (query) The order in which results are listed in the response (&#x60;ASC&#x60; for oldest first, &#x60;DESC&#x60; for newest first).  Default value: &#x60;DESC&#x60; (optional)     - parameter cursor: (query) A pagination cursor returned by a previous call to this endpoint. Provide this to retrieve the next set of results for your original query.  See [Pagination](/basics/api101/pagination) for more information. (optional)

     - returns: RequestBuilder<ListAdditionalRecipientReceivablesResponse> 
     */
    open class func listAdditionalRecipientReceivablesWithRequestBuilder(locationId: String, beginTime: String? = nil, endTime: String? = nil, sortOrder: String? = nil, cursor: String? = nil) -> RequestBuilder<ListAdditionalRecipientReceivablesResponse> {
        var path = "/v2/locations/{location_id}/additional-recipient-receivables"
        let locationIdPreEscape = "\(locationId)"
        let locationIdPostEscape = locationIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{location_id}", with: locationIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "begin_time": beginTime, 
                        "end_time": endTime, 
                        "sort_order": sortOrder, 
                        "cursor": cursor
        ])

        let requestBuilder: RequestBuilder<ListAdditionalRecipientReceivablesResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
